apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: model-serving
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: retrieval.hieugn.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 30000

        - path: /docs
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 30000

        - path: /openapi.json
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}
              port:
                number: 30000
