- name: Create a Compute Engine instance
  hosts: localhost
  tasks:
    - name: Start an instance
      gcp_compute_instance:
        name: instance-jenkins
        machine_type: e2-custom-2-4096
        zone: us-central1-a
        project: mlops-430311
        auth_kind: serviceaccount
        service_account_file: ../secrets/mlops-430311-f4c0a77dd919.json

        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230727
              disk_size_gb: 25

        network_interfaces:
          - network:
              selfLink: global/networks/default
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        state: present

    - name: Create inbound firewall rule for port 8081 and 50000
      gcp_compute_firewall:
        name: allow-port-8081-50000
        network:
          selfLink: global/networks/default
        allowed:
          - ip_protocol: TCP
            ports:
              - 8081
              - 50000
        source_ranges:
          - 0.0.0.0/0
        direction: INGRESS
        description: Allow incoming traffic on port 30000
        project: mlops-430311
        auth_kind: serviceaccount
        service_account_file: ../secrets/mlops-430311-f4c0a77dd919.json
